config/routes.rb
StreetReport02::Application.routes.draw do

  devise_for :users, :controllers => {:sessions => "devise/sessions", :registrations => "users"}

  root :to => "reports#index"

  resources :reports

  resources :users, :controller => "users" do
    resources :reports, shallow: true
  end

  match '/filter' => 'reports#filter', :as => 'filter'

  match '/reportsCount/:user_id(.:format)' => 'users#reportsCount', :as => 'reportsCount'

  resources :followers

  resources :statuses

  resources :comments

  resources :pictures

  resources :institutions

  resources :officers

end

app/models/institution.rb
class Institution < ActiveRecord::Base
  attr_accessible :basic_info, :logo, :name, :website

  has_many :reports
  has_many :officers
  has_many :users, through: :officers
end

app/controllers/institutions_controller.rb
class InstitutionsController < ApplicationController

  before_filter :authenticate_user!

  # GET /institutions
  # GET /institutions.json
  def index
    @institutions = Institution.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @institutions }
    end
  end

  # GET /institutions/1
  # GET /institutions/1.json
  def show
    @institution = Institution.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @institution }
    end
  end

  # GET /institutions/new
  # GET /institutions/new.json
  def new
    @institution = Institution.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @institution }
    end
  end

  # GET /institutions/1/edit
  def edit
    @institution = Institution.find(params[:id])
  end

  # POST /institutions
  # POST /institutions.json
  def create
    @institution = Institution.new(params[:institution])

    respond_to do |format|
      if @institution.save
        format.html { redirect_to @institution, notice: 'Institution was successfully created.' }
        format.json { render json: @institution, status: :created, location: @institution }
      else
        format.html { render action: "new" }
        format.json { render json: @institution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /institutions/1
  # PUT /institutions/1.json
  def update
    @institution = Institution.find(params[:id])

    respond_to do |format|
      if @institution.update_attributes(params[:institution])
        format.html { redirect_to @institution, notice: 'Institution was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @institution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /institutions/1
  # DELETE /institutions/1.json
  def destroy
    @institution = Institution.find(params[:id])
    @institution.destroy

    respond_to do |format|
      format.html { redirect_to institutions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/institutions_helper.rb
module InstitutionsHelper
end

app/views/institutions/_form.html.erb
<%= form_for(@institution) do |f| %>
  <% if @institution.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@institution.errors.count, "error") %> prohibited this institution from being saved:</h2>

      <ul>
      <% @institution.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :website %><br />
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :basic_info %><br />
    <%= f.text_area :basic_info %>
  </div>
  <div class="field">
    <%= f.label :logo %><br />
    <%= f.text_area :logo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/institutions/edit.html.erb
<h1>Editing institution</h1>

<%= render 'form' %>

<%= link_to 'Show', @institution %> |
<%= link_to 'Back', institutions_path %>

app/views/institutions/index.html.erb
<h1>Listing institutions</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Website</th>
    <th>Basic info</th>
    <th>Logo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @institutions.each do |institution| %>
  <tr>
    <td><%= institution.name %></td>
    <td><%= institution.website %></td>
    <td><%= institution.basic_info %></td>
    <td><%= institution.logo %></td>
    <td><%= link_to 'Show', institution %></td>
    <td><%= link_to 'Edit', edit_institution_path(institution) %></td>
    <td><%= link_to 'Destroy', institution, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Institution', new_institution_path %>

app/views/institutions/new.html.erb
<h1>New institution</h1>

<%= render 'form' %>

<%= link_to 'Back', institutions_path %>

app/views/institutions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @institution.name %>
</p>

<p>
  <b>Website:</b>
  <%= @institution.website %>
</p>

<p>
  <b>Basic info:</b>
  <%= @institution.basic_info %>
</p>

<p>
  <b>Logo:</b>
  <%= @institution.logo %>
</p>


<%= link_to 'Edit', edit_institution_path(@institution) %> |
<%= link_to 'Back', institutions_path %>