config/routes.rb
StreetReport02::Application.routes.draw do

  devise_for :users, :controllers => {:sessions => "devise/sessions", :registrations => "users"}

  root :to => "reports#index"

  resources :reports

  resources :users, :controller => "users" do
    resources :reports, shallow: true
  end

  match '/filter' => 'reports#filter', :as => 'filter'

  match '/reportsCount/:user_id(.:format)' => 'users#reportsCount', :as => 'reportsCount'

  resources :followers

  resources :statuses

  resources :comments

  resources :pictures

  resources :institutions

  resources :officers

end

app/models/follower.rb
class Follower < ActiveRecord::Base
  attr_accessible :rating, :report_id, :user_id

  belongs_to :report
  belongs_to :user
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController
  # GET /followers
  # GET /followers.json
  def index
    @followers = Follower.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @followers }
    end
  end

  # GET /followers/1
  # GET /followers/1.json
  def show
    @follower = Follower.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @follower }
    end
  end

  # GET /followers/new
  # GET /followers/new.json
  def new
    @follower = Follower.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @follower }
    end
  end

  # GET /followers/1/edit
  def edit
    @follower = Follower.find(params[:id])
  end

  # POST /followers
  # POST /followers.json
  def create
    @follower = Follower.new(params[:follower])

    respond_to do |format|
      if @follower.save
        format.html { redirect_to @follower, notice: 'Follower was successfully created.' }
        format.json { render json: @follower, status: :created, location: @follower }
      else
        format.html { render action: "new" }
        format.json { render json: @follower.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /followers/1
  # PUT /followers/1.json
  def update
    @follower = Follower.find(params[:id])

    respond_to do |format|
      if @follower.update_attributes(params[:follower])
        format.html { redirect_to @follower, notice: 'Follower was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @follower.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /followers/1
  # DELETE /followers/1.json
  def destroy
    @follower = Follower.find(params[:id])
    @follower.destroy

    respond_to do |format|
      format.html { redirect_to followers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/views/followers/_form.html.erb
<%= form_for(@follower) do |f| %>
  <% if @follower.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@follower.errors.count, "error") %> prohibited this follower from being saved:</h2>

      <ul>
      <% @follower.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rating %><br />
    <%= f.number_field :rating %>
  </div>
  <div class="field">
    <%= f.label :report_id %><br />
    <%= f.number_field :report_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/followers/edit.html.erb
<h1>Editing follower</h1>

<%= render 'form' %>

<%= link_to 'Show', @follower %> |
<%= link_to 'Back', followers_path %>

app/views/followers/index.html.erb
<h1>Listing followers</h1>

<table>
  <tr>
    <th>Rating</th>
    <th>Report</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @followers.each do |follower| %>
  <tr>
    <td><%= follower.rating %></td>
    <td><%= follower.report_id %></td>
    <td><%= follower.user_id %></td>
    <td><%= link_to 'Show', follower %></td>
    <td><%= link_to 'Edit', edit_follower_path(follower) %></td>
    <td><%= link_to 'Destroy', follower, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Follower', new_follower_path %>

app/views/followers/new.html.erb
<h1>New follower</h1>

<%= render 'form' %>

<%= link_to 'Back', followers_path %>

app/views/followers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Rating:</b>
  <%= @follower.rating %>
</p>

<p>
  <b>Report:</b>
  <%= @follower.report_id %>
</p>

<p>
  <b>User:</b>
  <%= @follower.user_id %>
</p>


<%= link_to 'Edit', edit_follower_path(@follower) %> |
<%= link_to 'Back', followers_path %>