config/routes.rb
StreetReport02::Application.routes.draw do

  devise_for :users, :controllers => {:sessions => "devise/sessions", :registrations => "users"}

  root :to => "reports#index"

  resources :reports

  resources :users, :controller => "users" do
    resources :reports, shallow: true
  end

  match '/filter' => 'reports#filter', :as => 'filter'

  match '/reportsCount/:user_id(.:format)' => 'users#reportsCount', :as => 'reportsCount'

  resources :followers

  resources :statuses

  resources :comments

  resources :pictures

  resources :institutions

  resources :officers

end

app/models/report.rb
class Report < ActiveRecord::Base
  attr_accessible :date_created, :date_updated, :description, :institution_id, :location, :status_id, :troubles_caused, :user_id

  belongs_to :institution
  belongs_to :user
  belongs_to :status
  has_many :pictures
  has_many :comments
  has_many :followers
  #has_many :user, through: :followers
end

app/controllers/reports_controller.rb
require 'reports_helper.rb'

class ReportsController < ApplicationController

  before_filter :authenticate_user!, :only => [:edit, :update, :destroy]

  helper_method :can_edit

  # GET /reports
  # GET /reports.json
  def index

    if params[:user_id]
      @reports = User.find(params[:user_id]).reports.order("created_at DESC")
    else

      @reports = Report.order("created_at DESC")
    end


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reports }
      format.xml { render xml: @reports }
    end
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    @report = Report.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @report }
      format.xml { render xml: @report }
    end
  end

  # GET /reports/new
  # GET /reports/new.json
  def new
    @report = Report.new
    @reports = Report.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @report }
      format.xml { render xml: @report }
    end
  end

  # GET /reports/1/edit
  def edit

    @report = Report.find(params[:id])

     redirect_to root_path, notice: "Sorry, you can't edit this report." unless can_edit(@report.user_id, user_signed_in?, current_user)

  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(params[:report])

    if user_signed_in?
      @report.user_id = current_user.id
    else
      @report.user_id = nil
    end

    @report.date_created = Time.now
    @report.date_updated = Time.now

    respond_to do |format|
      if @report.save
        #format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.html { redirect_to root_path, notice: 'Report was successfully created.' }
        format.json { render json: @report, status: :created, location: @report }
        format.xml { render xml: @report, status: :created, location: @report }
      else
        format.html { render action: "new" }
        format.json { render json: @report.errors, status: :unprocessable_entity }
        format.xml { render xml: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reports/1
  # PUT /reports/1.json
  def update
    @report = Report.find(params[:id])

    respond_to do |format|
      if @report.update_attributes(params[:report])
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { head :no_content }
        format.xml { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @report.errors, status: :unprocessable_entity }
        format.xml { render xml: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report = Report.find(params[:id])
    @report.destroy

    redirect_to root_path, notice: "Sorry, you can't delete this report." unless can_edit(@report.user_id, user_signed_in?, current_user)

    respond_to do |format|
      format.html { redirect_to reports_url }
      format.json { head :no_content }
    end
  end

  def filter

    @reports = Report.where("description like ? OR location like ?", "%#{params[:filter][:search]}%", "%#{params[:filter][:search]}%").order("created_at DESC")


    render 'index'


  end



  #private
  def can_edit(user_id, user_signed_in, current_user)

    return false unless user_signed_in

    if current_user.id == user_id || current_user.email == "admin@admin.com"
      return true
    end
  end


  def self.author(report)

    return "Anonymous" unless report.user_id != nil

    report.user.complete_name
  end



end

app/helpers/reports_helper.rb
module ReportsHelper

=begin
  class Filter
    #attr_accessible :search, :status, :date_created_updated, :date_before_after

    def search
      @search
    end
    def status
      @status
    end
  end
=end

end

app/views/reports/_filter.html.erb
<div class="section_title">
  Report Filter
</div>


<%= form_for :filter, url: filter_path do |f| %>

    <p>
      <%= f.label :search %> <br>      <!-- must search in accountable institution, report description, location, troubles caused  -->
      <%= f.text_field :search %>
    </p>





    <%= f.submit :filter%>


<% end %>






app/views/reports/_form.html.erb
<%= form_for(@report) do |f| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% @report.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'What I saw' %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :troubles_caused %><br />
    <%= f.text_area :troubles_caused %>
  </div>


  <div class="field">
    <%= f.label :institution_id %><br />
    <%= f.number_field :institution_id %>
  </div>
  <div class="field">
    <%= f.label :status_id %><br />
    <%= f.number_field :status_id %>
  </div>

  <% if @report.user_id && @report.user_id != "" %>
        <p>
          <b>User:</b>
          <%= ReportsController.author(@report) %>
        </p>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/reports/_form_new.html.erb
<%= form_for(@report) do |f| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% @report.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :description, 'What I saw' %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :troubles_caused %><br />
    <%= f.text_area :troubles_caused %>
  </div>





  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/reports/_list_of_reports.html.erb
<% @reports.each do |report| %>
    <div id="<%= "report_#{report.id}"%> " class="report">

      <div id="<%="location_#{report.id}"%>" class="location">
        <b>Location</b>
        <br>
        <%= report.location %>
      </div>

      <div id="description_#{report.id}" class="description">
        <b>What the Reporter Saw</b>
        <br>
        <%= report.description %>
      </div>



      <div id="status_#{report.id}" class="status">

        <%= report.status_id %>
      </div>




      <div id="institution_#{report.id}" class="institution">


        <%= report.institution_id %>
      </div>

      <div id="reporter_#{report.id}" class="reporter">
        By

        <%= ReportsController.author(report) %>
      </div>





      <div id="actions_#{report.id}" class="actions">
        <%= link_to 'Show', report, :class => "show" %>


        <% if can_edit(report.user_id, user_signed_in?, current_user)%>

            <%= link_to 'Edit', edit_report_path(report), :class => "edit" %>


            <%= link_to 'Destroy', report,  method: :delete, data: { confirm: 'Are you sure?' }, :class => "destroy" %>

        <% end %>

        <div id="updated_#{report.id}" class="updated">
          <%= report.date_updated.to_date %>
        </div>




      </div>

      <div class="report_footer">

      </div>
    </div>




<% end %>

app/views/reports/edit.html.erb
<h1>Editing report</h1>

<%= render 'form' %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<div id="menu" class="menu">

  <% if current_user %>
    <%= link_to 'My Reports', user_reports_path(current_user.id) %>    <br>   <br>
    <%= link_to("How many reports do I have?", "/reportsCount/#{current_user.id}.json" , :method => :get, remote: true) %>
    <label id="reportsCountLabel" />
  <% end %>
</div>




<div id="content" class="content">




  <a href="<%= new_report_path %>">
  <div id="new_report_button" >
    New Report
  </div>
  </a>


  <h1>Most Recent Reports</h1>



      <%= render 'list_of_reports' %>






    <br />

</div>

<div class="sidebar">

  <%= render 'filter' %>
</div>

app/views/reports/new.html.erb
<h1>New report</h1>

<div id="content" class="content-thin">
    <%= render 'form_new' %>

    <%= link_to 'Back', reports_path %>



</div>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Date created:</b>
  <%= @report.date_created %>
</p>

<p>
  <b>Date updated:</b>
  <%= @report.date_updated %>
</p>

<p>
  <b>Description:</b>
  <%= @report.description %>
</p>

<p>
  <b>Location:</b>
  <%= @report.location %>
</p>

<p>
  <b>Troubles caused:</b>
  <%= @report.troubles_caused %>
</p>

<p>
  <b>Institution:</b>
  <%= @report.institution_id %>
</p>

<p>
  <b>Status:</b>
  <%= @report.status_id %>
</p>

<p>
  <b>User:</b>
  <%= ReportsController.author(@report)  %>
</p>

<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>

app/views/reports/similar.html.erb
<h1>Similar Reports</h1>

<%= render 'form' %>

<%= link_to 'Back', reports_path %>

<div id="suggested_reports">
  <form  method="GET">
    <!-- This should be ajax -->
    <input type="submit" action="/similar" value="Look for Similar Reports"   >
  </form>
</div>